management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springmysql
    password: '2444'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Learning Spring-Boot!